import type { Place, Signal, Event, PlaceCategory } from '@/types';

const NAIROBI_CENTER = { lat: -1.2921, lng: 36.8219 };

function randomNear(
  center: { lat: number; lng: number },
  radiusM: number
): { lat: number; lng: number } {
  const r = radiusM / 111320;
  const angle = Math.random() * 2 * Math.PI;
  const distance = Math.random() * r;
  return {
    lat: center.lat + distance * Math.cos(angle),
    lng: center.lng + (distance * Math.sin(angle)) / Math.cos((center.lat * Math.PI) / 180),
  };
}

export const MOCK_PLACES: Place[] = [
  {
    id: 'plc_001',
    name: 'Mamba Village Nairobi',
    category: 'food' as PlaceCategory,
    subcategory: 'restaurant',
    description:
      'A serene lakeside restaurant famous for fresh seafood and Nyama Choma. Perfect for family lunches with a view of the crocodile farm.',
    latitude: -1.3512,
    longitude: 36.7496,
    distanceM: 8520,
    walkingTimeMin: 106,
    address: 'Langata Road, Nairobi',
    city: 'Nairobi',
    country: 'KE',
    priceMin: 1500,
    priceMax: 5000,
    amenities: ['wifi', 'parking', 'outdoor_seating', 'family_friendly'],
    scores: {
      safety: 8,
      affordability: 7,
      popularity: 9,
      nightlife: 3,
      familyFriendliness: 9,
      cleanliness: 8,
      accessibility: 7,
      walkability: 5,
    },
    source: 'manual',
    isFeatured: false,
    isGem: true,
    gemExplanation:
      'A hidden treasure known mostly to locals — the crocodile feeding spectacle at sunset makes this more than just a meal.',
    reviewCount: 340,
    averageRating: 4.3,
    monthlyVisitors: 8200,
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'plc_002',
    name: 'The Alchemist Bar',
    category: 'entertainment' as PlaceCategory,
    subcategory: 'bar',
    description:
      'Westlands premium cocktail bar with rooftop views, live DJ sets, and an art gallery. The creative crowd\'s favorite spot.',
    latitude: -1.2645,
    longitude: 36.8047,
    distanceM: 3200,
    walkingTimeMin: 40,
    address: 'Parklands Road, Westlands, Nairobi',
    city: 'Nairobi',
    country: 'KE',
    priceMin: 800,
    priceMax: 6000,
    amenities: ['wifi', 'parking', 'rooftop', 'live_music', 'art_gallery'],
    scores: {
      safety: 9,
      affordability: 5,
      popularity: 9,
      nightlife: 10,
      walkability: 8,
      cleanliness: 8,
      internetSpeed: 9,
    },
    source: 'manual',
    isFeatured: true,
    isGem: false,
    gemExplanation: null,
    reviewCount: 1200,
    averageRating: 4.6,
    monthlyVisitors: 15000,
    imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&h=400&fit=crop',
    createdAt: '2023-08-22T10:00:00Z',
  },
  {
    id: 'plc_003',
    name: 'Karura Forest Reserve',
    category: 'outdoor' as PlaceCategory,
    subcategory: 'park',
    description:
      '1,000 hectares of urban forest with walking trails, bike paths, waterfalls, and caves. A peaceful escape inside the city.',
    latitude: -1.2325,
    longitude: 36.8325,
    distanceM: 6200,
    walkingTimeMin: 77,
    address: 'Limuru Road, Nairobi',
    city: 'Nairobi',
    country: 'KE',
    priceMin: 200,
    priceMax: 600,
    amenities: ['parking', 'bike_trails', 'walking_trails', 'waterfall', 'picnic_areas'],
    scores: {
      safety: 9,
      affordability: 9,
      popularity: 8,
      familyFriendliness: 9,
      cleanliness: 8,
      walkability: 9,
      petFriendliness: 7,
    },
    source: 'manual',
    isFeatured: false,
    isGem: false,
    gemExplanation: null,
    reviewCount: 5200,
    averageRating: 4.7,
    monthlyVisitors: 35000,
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&h=400&fit=crop',
    createdAt: '2023-01-10T10:00:00Z',
  },
  {
    id: 'plc_004',
    name: 'K1 Klub House',
    category: 'entertainment' as PlaceCategory,
    subcategory: 'club',
    description:
      'Iconic nightlife destination on Ojijo Road. Seven bars, a massive dance floor, and themed nights. The place to be seen.',
    latitude: -1.2645,
    longitude: 36.8015,
    distanceM: 3400,
    walkingTimeMin: 42,
    address: 'Ojijo Road, Parklands, Nairobi',
    city: 'Nairobi',
    country: 'KE',
    priceMin: 1000,
    priceMax: 10000,
    amenities: ['parking', 'vip_lounge', 'live_dj'],
    scores: {
      safety: 7,
      affordability: 6,
      popularity: 8,
      nightlife: 10,
      walkability: 7,
      accessibility: 8,
    },
    source: 'manual',
    isFeatured: false,
    isGem: false,
    gemExplanation: null,
    reviewCount: 2800,
    averageRating: 4.1,
    monthlyVisitors: 22000,
    imageUrl: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&h=400&fit=crop',
    createdAt: '2023-03-05T10:00:00Z',
  },
  {
    id: 'plc_005',
    name: 'Artcaffé Westgate',
    category: 'food' as PlaceCategory,
    subcategory: 'cafe',
    description:
      'Premium café chain serving specialty coffee, fresh pastries, and contemporary cuisine in a stylish setting.',
    latitude: -1.2557,
    longitude: 36.7864,
    distanceM: 5100,
    walkingTimeMin: 63,
    address: 'Westgate Shopping Mall, Mwanzi Road, Nairobi',
    city: 'Nairobi',
    country: 'KE',
    priceMin: 500,
    priceMax: 2500,
    amenities: ['wifi', 'parking', 'outdoor_seating', 'vegetarian_options'],
    scores: {
      safety: 9,
      affordability: 7,
      popularity: 9,
      walkability: 7,
      cleanliness: 9,
      internetSpeed: 9,
      accessibility: 9,
    },
    source: 'manual',
    isFeatured: false,
    isGem: false,
    gemExplanation: null,
    reviewCount: 4500,
    averageRating: 4.4,
    monthlyVisitors: 28000,
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&h=400&fit=crop',
    createdAt: '2023-06-18T10:00:00Z',
  },
  {
    id: 'plc_006',
    name: 'The Hub Karen',
    category: 'shopping' as PlaceCategory,
    subcategory: 'mall',
    description:
      'Boutique open-air mall in Karen with premium fashion brands, artisan markets, and al fresco dining.',
    latitude: -1.3873,
    longitude: 36.7423,
    distanceM: 14200,
    walkingTimeMin: 177,
    address: 'Dagoretti Road, Karen, Nairobi',
    city: 'Nairobi',
    country: 'KE',
    priceMin: 500,
    priceMax: 50000,
    amenities: ['parking', 'wifi', 'wheelchair_accessible', 'playground'],
    scores: {
      safety: 9,
      affordability: 6,
      popularity: 7,
      walkability: 7,
      cleanliness: 9,
      accessibility: 9,
      familyFriendliness: 8,
    },
    source: 'manual',
    isFeatured: false,
    isGem: false,
    gemExplanation: null,
    reviewCount: 1800,
    averageRating: 4.5,
    monthlyVisitors: 32000,
    imageUrl: 'https://images.unsplash.com/photo-1567449303078-57ad995bd17b?w=600&h=400&fit=crop',
    createdAt: '2023-11-02T10:00:00Z',
  },
  {
    id: 'plc_007',
    name: 'Aga Khan University Hospital',
    category: 'essentials' as PlaceCategory,
    subcategory: 'hospital',
    description:
      'World-class private hospital with 24/7 emergency services, specialist clinics, and advanced diagnostic facilities.',
    latitude: -1.2612,
    longitude: 36.8261,
    distanceM: 3100,
    walkingTimeMin: 38,
    address: '3rd Parklands Avenue, Nairobi',
    city: 'Nairobi',
    country: 'KE',
    priceMin: 3000,
    priceMax: 500000,
    amenities: ['parking', 'wheelchair_accessible', '24_7', 'pharmacy'],
    scores: {
      safety: 9,
      affordability: 4,
      popularity: 8,
      cleanliness: 10,
      accessibility: 9,
      walkability: 5,
    },
    source: 'manual',
    isFeatured: false,
    isGem: false,
    gemExplanation: null,
    reviewCount: 3200,
    averageRating: 4.5,
    monthlyVisitors: 45000,
    imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600&h=400&fit=crop',
    createdAt: '2023-02-14T10:00:00Z',
  },
  {
    id: 'plc_008',
    name: 'Penthouse Apartments Kilimani',
    category: 'property' as PlaceCategory,
    subcategory: 'apartment',
    description:
      'Luxury 3-bedroom penthouse with panoramic city views, infinity pool, gym, and 24/7 security in prime Kilimani.',
    latitude: -1.2957,
    longitude: 36.7918,
    distanceM: 3800,
    walkingTimeMin: 47,
    address: 'Kilimani Road, Nairobi',
    city: 'Nairobi',
    country: 'KE',
    priceMin: 85000,
    priceMax: 180000,
    amenities: ['pool', 'gym', 'security', 'parking', 'backup_generator'],
    scores: {
      safety: 9,
      affordability: 3,
      popularity: 6,
      investmentPotential: 9,
      walkability: 7,
      cleanliness: 9,
      internetSpeed: 8,
    },
    source: 'manual',
    isFeatured: true,
    isGem: false,
    gemExplanation: null,
    reviewCount: 45,
    averageRating: 4.8,
    monthlyVisitors: 500,
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop',
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'plc_009',
    name: 'Nairobi Street Kitchen',
    category: 'food' as PlaceCategory,
    subcategory: 'street_food',
    description:
      'A curated collective of 11 street food vendors in a beautifully restored godown. Global flavors in an artsy setting.',
    latitude: -1.2645,
    longitude: 36.8072,
    distanceM: 3800,
    walkingTimeMin: 47,
    address: 'Museum Hill, Nairobi',
    city: 'Nairobi',
    country: 'KE',
    priceMin: 300,
    priceMax: 1500,
    amenities: ['wifi', 'parking', 'outdoor_seating', 'live_music'],
    scores: {
      safety: 8,
      affordability: 8,
      popularity: 8,
      nightlife: 7,
      walkability: 6,
      cleanliness: 7,
      accessibility: 7,
    },
    source: 'manual',
    isFeatured: false,
    isGem: true,
    gemExplanation:
      'Tucked behind the National Museum, this converted warehouse hides 11 kitchens serving everything from Korean tacos to Ethiopian injera.',
    reviewCount: 620,
    averageRating: 4.5,
    monthlyVisitors: 12000,
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop',
    createdAt: '2023-09-08T10:00:00Z',
  },
  {
    id: 'plc_010',
    name: 'Westgate Spa & Wellness',
    category: 'lifestyle' as PlaceCategory,
    subcategory: 'spa',
    description:
      'Award-winning day spa offering Swedish massage, aromatherapy, facials, and hydrotherapy. An oasis of calm in the city.',
    latitude: -1.2555,
    longitude: 36.7872,
    distanceM: 5100,
    walkingTimeMin: 63,
    address: 'Westgate Mall, 5th Floor, Mwanzi Road',
    city: 'Nairobi',
    country: 'KE',
    priceMin: 3000,
    priceMax: 15000,
    amenities: ['wifi', 'parking', 'couples_room', 'sauna', 'steam_room'],
    scores: {
      safety: 9,
      affordability: 5,
      popularity: 7,
      cleanliness: 10,
      accessibility: 9,
      walkability: 7,
    },
    source: 'manual',
    isFeatured: false,
    isGem: false,
    gemExplanation: null,
    reviewCount: 890,
    averageRating: 4.7,
    monthlyVisitors: 3500,
    imageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&h=400&fit=crop',
    createdAt: '2023-04-11T10:00:00Z',
  },
];

export const MOCK_SIGNALS: Signal[] = [
  {
    id: 'sig_001',
    type: 'new_place',
    placeId: 'plc_008',
    title: 'New listing: Penthouse Apartments Kilimani',
    body: 'Luxury 3-bedroom penthouse just listed in Kilimani. Panoramic views, infinity pool.',
    score: 0.92,
    expiresAt: '2024-03-15T10:00:00Z',
    createdAt: '2024-03-08T08:15:00Z',
  },
  {
    id: 'sig_002',
    type: 'event_upcoming',
    placeId: 'plc_002',
    title: 'Friday Live Jazz Night at The Alchemist',
    body: 'Live jazz ensemble featuring Nairobi\'s top musicians. Happy hour cocktails 5-7 PM.',
    score: 0.87,
    expiresAt: '2024-03-09T23:00:00Z',
    createdAt: '2024-03-08T06:00:00Z',
  },
  {
    id: 'sig_003',
    type: 'promotion',
    placeId: 'plc_010',
    title: '50% off couples massage at Westgate Spa',
    body: 'Book a couples massage this weekend and get the second treatment half price.',
    score: 0.76,
    expiresAt: '2024-03-10T22:00:00Z',
    createdAt: '2024-03-08T09:30:00Z',
  },
  {
    id: 'sig_004',
    type: 'price_drop',
    placeId: 'plc_001',
    title: 'Mamba Village lunch special — prices down 20%',
    body: 'Weekday lunch menu now starting at KSh 1,200. Crocodile feeding included.',
    score: 0.81,
    expiresAt: '2024-03-15T10:00:00Z',
    createdAt: '2024-03-07T12:00:00Z',
  },
  {
    id: 'sig_005',
    type: 'trending',
    placeId: 'plc_009',
    title: 'Nairobi Street Kitchen is heating up 🔥',
    body: 'Visitor traffic up 340% this week. Korean-Mexican fusion stall going viral.',
    score: 0.94,
    expiresAt: '2024-03-12T10:00:00Z',
    createdAt: '2024-03-08T14:20:00Z',
  },
  {
    id: 'sig_006',
    type: 'availability',
    placeId: 'plc_008',
    title: 'Weekend viewing slots open at Penthouse Apartments',
    body: '3 viewing slots available this Saturday. Book now before they\'re gone.',
    score: 0.72,
    expiresAt: '2024-03-09T18:00:00Z',
    createdAt: '2024-03-08T07:00:00Z',
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'evt_001',
    title: 'Nairobi Restaurant Week 2024',
    description:
      'A 10-day culinary festival featuring prix-fixe menus at 50+ of Nairobi\'s best restaurants. Explore the city\'s diverse food scene at special prices.',
    venueId: 'plc_005',
    startTime: '2024-03-15T10:00:00Z',
    endTime: '2024-03-24T22:00:00Z',
    category: 'food',
    priceMin: 1200,
    priceMax: 4500,
    source: 'manual',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop',
    ticketUrl: null,
  },
  {
    id: 'evt_002',
    title: 'Live at the Alchemist: Sauti Sol Acoustic',
    description:
      'Kenya\'s biggest band performs an intimate acoustic set on the rooftop. Limited tickets available.',
    venueId: 'plc_002',
    startTime: '2024-03-16T19:00:00Z',
    endTime: '2024-03-16T23:00:00Z',
    category: 'music',
    priceMin: 3000,
    priceMax: 8000,
    source: 'manual',
    imageUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&h=400&fit=crop',
    ticketUrl: 'https://example.com/tickets/sauti-sol',
  },
  {
    id: 'evt_003',
    title: 'Karura Forest Trail Run',
    description:
      'Monthly 10K and 21K trail run through Karura Forest. All fitness levels welcome. Finisher medals for all participants.',
    venueId: 'plc_003',
    startTime: '2024-03-17T06:30:00Z',
    endTime: '2024-03-17T10:00:00Z',
    category: 'sports',
    priceMin: 500,
    priceMax: 1500,
    source: 'manual',
    imageUrl: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=600&h=400&fit=crop',
    ticketUrl: 'https://example.com/tickets/karura-run',
  },
  {
    id: 'evt_004',
    title: 'Saturday Flea Market at The Hub Karen',
    description:
      'Curated artisan market with handmade crafts, vintage clothing, organic produce, and live acoustic music. Every Saturday.',
    venueId: 'plc_006',
    startTime: '2024-03-09T09:00:00Z',
    endTime: '2024-03-09T17:00:00Z',
    category: 'market',
    priceMin: 0,
    priceMax: 0,
    source: 'manual',
    imageUrl: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&h=400&fit=crop',
    ticketUrl: null,
  },
];